name: My First Workflow
# We specify when it should run (here for example when we push to the main bransh) 
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Print a message
      run: echo "Hello, world!"